export const fakeUsers = [
  {
    email: 'user01@example.com',
    username: 'racer123',
    money: 100.5,
    name: 'John Doe',
    id: 0,
  },
  {
    email: 'user02@example.com',
    username: 'fastfreddy',
    money: 50.0,
    name: 'Jane Smith',
  },
  {
    email: 'user03@example.com',
    username: 'speeddemon',
    money: 25.75,
    name: 'Peter Jones',
  },
  {
    email: 'user04@example.com',
    username: 'trackstar',
    money: 68.3,
    name: 'Mary Brown',
  },
  {
    email: 'user05@example.com',
    username: 'cornermaster',
    money: 92.15,
    name: 'David Miller',
  },
  {
    email: 'user06@example.com',
    username: 'gearhead',
    money: 41.4,
    name: 'Susan Williams',
  },
  {
    email: 'user07@example.com',
    username: 'adrenalinejunkie',
    money: 105.95,
    name: 'Robert Thompson',
  },
  {
    email: 'user08@example.com',
    username: 'overtakeking',
    money: 37.6,
    name: 'Anna Anderson',
  },
  {
    email: 'user09@example.com',
    username: 'pitcrewchief',
    money: 81.25,
    name: 'Thomas Moore',
  },
  {
    email: 'user10@example.com',
    username: 'checkeredflag',
    money: 53.8,
    name: 'Elizabeth Harris',
  },
  {
    email: 'user11@example.com',
    username: 'nitrofan',
    money: 117.45,
    name: 'Christopher Lee',
  },
  {
    email: 'user12@example.com',
    username: 'apexartist',
    money: 70.1,
    name: 'Karen Garcia',
  },
  {
    email: 'user13@example.com',
    username: 'gforceexpert',
    money: 123.75,
    name: 'Michael Walker',
  },
  {
    email: 'user14@example.com',
    username: 'tirewhisperer',
    money: 46.4,
    name: 'Jennifer Davis',
  },
  {
    email: 'user15@example.com',
    username: 'podiumchaser',
    money: 99.05,
    name: 'Kevin Baker',
  },
  {
    email: 'user16@example.com',
    username: 'racetrackruler',
    money: 62.7,
    name: 'Sandra Jones',
  },
  {
    email: 'user17@example.com',
    username: 'speedspecialist',
    money: 116.35,
    name: 'Mark Robinson',
  },
  {
    email: 'user18@example.com',
    username: 'trickmaster',
    money: 39.0,
    name: 'Charles Taylor',
  },
  {
    email: 'user19@example.com',
    username: 'overtakingmaestro',
    money: 82.65,
    name: 'Paul Smith',
  },
  {
    email: 'user20@example.com',
    username: 'speedster20',
    money: 75.25,
    name: 'Mark Johnson',
  },
];
